settings:
  title: 'Rotaract Mora | Cyber Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: rotaractmora-blog # unique identifier
    name: blog.rotaractmora.org
    description: 'Official Blog of Rotaract Mora' # default=empty
    url: 'https://blog.rotaractmora.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: rotaractmora-web
    name: rotaractmora.org
    description: 'Official Website of RotaractMora'
    url: 'https://www.rotaractmora.org'
    followRedirect: true
    method: GET
    expectStatus: 200

  - id: rotaractmora-linkR
    name: LinkR Platform
    url: 'https://linkr.rotaractmora.org/'
    method: GET
    expectStatus: 200

  - id: rotaractmora-manusath-contrib-0
    name: Manusath Handa | Contributors Portal
    url:  'https://portal.manusathhanda.rotaractmora.org'
    followRedirect: true
    method: GET
    expectStatus: 200

  - id: rotaractmora-mun
    name: Rotaract Mora MUN
    url: 'http://mun.rotaractmora.org/'
    method: GET
    expectStatus: 200

  - id: rotaractmora-manusath
    name: Manusath Handa E-Library
    url: 'https://manusathhanda.rotaractmora.org/'
    method: GET
    expectStatus: 200

  - id: rotaractmora-nena-aruna
    name: Nena Aruna
    url: 'https://nenaaruna.rotaractmora.org/'
    method: GET
    expectStatus: 200

  - id: rotaractmora-learnyou
    name: Learn You
    url: 'https://learnyou.rotaractmora.org/'
    method: GET
    expectStatus: 200
  
  - id: rotaractmora-rur
    name: Are You Ready Platform
    url: 'https://rur.rotaract.social/'
    method: GET
    expectStatus: 200

  - id: rotaract-social-platform
    name: Social Links
    url: 'https://rotaract.social'
    method: GET
    followRedirect: true
    expectStatus: 200

  - id: rotaractmora-indiretto
    name: Indiretto
    url: 'https://indiretto.rotaractmora.org/'
    method: GET
    expectStatus: 200

  - id: rotaractmora-scholar
    name: Scholar
    url: 'https://scholar.rotaractmora.org/'
    method: GET
    expectStatus: 200

  - id: cast4
    name: CAST4 Website
    url: 'http://cast4.rotaractmora.org/'
    method: GET
    expectStatus: 200

  - id: datastorm
    name: DataStorm Website
    url: 'https://datastorm.rotaract.social'
    method: GET
    expectStatus: 200