settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: rotaractmora-blog # unique identifier
    name: blog.rotaractmora.org
    description: 'Official Blog of Rotaract Mora' # default=empty
    url: 'https://blog.rotaractmora.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: rotaractmora-web
    name: rotaractmora.org
    description: 'Official Website of RotaractMora'
    url: 'https://www.rotaractmora.org'
    method: GET
    expectStatus: 200

  - id: rotaractmora-linkR
    name: LinkR Platform
    url: 'https://linkr.rotaractmora.org/'
    method: GET
    expectStatus: 200
